# permissions for end users to view istio.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: istio-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: istio
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/managed-by: kustomize
  name: istio-viewer-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - istios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - istios/status
  verbs:
  - get
- apiGroups:
  - networking.istio.io
  verbs:
    - get
    - list
    - watch
  resources:
    - DestinationRule
    - EnvoyFilter
    - Gateway
    - ProxyConfig
    - ServiceEntry
    - Sidecar
    - VirtualService
    - WorkloadEntry
    - WorkloadGroup
- apiGroups:
    - security.istio.io
  verbs:
    - get
    - list
    - watch
  resources:
    - AuthorizationPolicy
    - PeerAuthentication
    - RequestAuthentication
- apiGroups:
    - install.istio.io
  verbs:
    - get
    - list
    - watch
  resources:
    - IstioOperator
- apiGroups:
    - telemetry.istio.io
  verbs:
    - get
    - list
    - watch
  resources:
    - Telemetry
- apiGroups:
    - extensions.istio.io
  verbs:
    - get
    - list
    - watch
  resources:
    - WasmPlugin
