# This workflow is responsible for all kinds of integration tests that are run after push to main.
# Those tests depend on a container image so in the first job we wait for the image build to succeed.

name: main integration tests

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "tests/performance/**"
      - "OWNERS"
      - "CODEOWNERS"
      - "sec-scanners-config.yaml"
      - ".github/**" #Ignoring since build job isn't triggered on the workflow directory changes
    branches:
      - main

jobs:

  istio-upgrade-integration-test:
    name: Istio upgrade integration test
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/upgrade-integration-test
        with:
          operator-image-name: "europe-docker.pkg.dev/kyma-project/prod/istio-manager:v20240122-fe11aa2c"
          target_branch: ${{github.ref_name}}

  istio-integration-test:
    name: Istio integration test
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/integration-test
        with:
          operator-image-name: "europe-docker.pkg.dev/kyma-project/prod/istio-manager:v20240122-fe11aa2c"
          servers-memory: "16g"
          agents: 2

  istio-performance-test:
    name: Istio performance test
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./tests/integration/scripts/gardener-kubeconfig.sh
        shell: bash
        env:
          GARDENER_TOKEN: ${{ secrets.GARDENER_TOKEN }}
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: make IMG=${{ europe-docker.pkg.dev/kyma-project/prod/istio-manager:v20240122-fe11aa2c }} gardener-perf-test
        shell: bash
        env:
          GARDENER_KUBECONFIG: "gardener_kubeconfig.yaml"
          GARDENER_PROJECT_NAME: "goatz"
          GARDENER_PROVIDER_SECRET_NAME: "goat"
          GARDENER_PROVIDER: "gcp"
          GARDENER_REGION: "europe-west3"
          GARDENER_CLUSTER_VERSION: "1.27"
          GARDENER_ZONES: "europe-west3-c,europe-west3-b,europe-west3-a"
          MACHINE_TYPE: "n2-standard-4"
          DISK_SIZE: 50
          DISK_TYPE: "pd-standard"
          SCALER_MAX: 20
          SCALER_MIN: 3

  istio-integration-gcp:
    name: Istio integration test GCP
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./tests/integration/scripts/gardener-kubeconfig.sh
        shell: bash
        env:
          GARDENER_TOKEN: ${{ secrets.GARDENER_TOKEN }}
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: make IMG=${{ europe-docker.pkg.dev/kyma-project/prod/istio-manager:v20240122-fe11aa2c }} gardener-istio-integration-test
        shell: bash
        env:
          GARDENER_KUBECONFIG: "gardener_kubeconfig.yaml"
          GARDENER_PROJECT_NAME: "goatz"
          GARDENER_PROVIDER_SECRET_NAME: "goat"
          GARDENER_PROVIDER: "gcp"
          GARDENER_CLUSTER_VERSION: "1.27"
          GARDENER_REGION: "europe-west3"
          GARDENER_ZONES: "europe-west3-c,europe-west3-b,europe-west3-a"
          MACHINE_TYPE: "n2-standard-4"
          DISK_SIZE: 50
          DISK_TYPE: "pd-standard"
          SCALER_MAX: 20
          SCALER_MIN: 3

  slack_failed_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [istio-upgrade-integration-test, istio-integration-test,  istio-integration-gcp, istio-performance-test]
    steps:
      - uses: actions/checkout@v4
      - name: Notify
        uses: ./.github/actions/slack-notification-failed-workflow
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
