name: Pull Request pipeline
on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]
    branches:
      - main
      - 'release-**'
jobs:
  wait-for-image-build:
    name: Wait for image build
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        id: changed-files
        with:
          files_ignore_yaml: |
            docs:
              - docs/**
              - '**.md'
            yaml:
              - '**.yaml'
            performance_tests:
              - tests/performance/**
            owner_files:
              - OWNERS
              - CODEOWNERS
            github_and_reuse:
              - .github/**
              - .reuse/**
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
      - uses: ./.github/actions/wait-for-job-succeed-or-fail
        if: ${{ steps.changed-files.outputs.any_modified }}
        with:
          job-name: 'pull-istio-operator-build'
          github-auth-token: ${{ secrets.GITHUB_TOKEN }}

  check-unit-test:
    name: Check whether unit test & lint should run based on the changed files
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        id: changed-files
        with:
          files_ignore_yaml: |
            docs:
              - docs/**
              - '**/*.md'
            performance_tests:
              - tests/performance/**
            owner_files:
              - OWNERS
              - CODEOWNERS
            sec_scanners:
              - sec-scanners-config.yaml
            dependabot:
              - ./github/dependabot.yml
            github_and_reuse:
              - .github/**
              - .reuse/**
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
  dispatch-unit-test:
    name: Dispatch unit test
    needs: [check-unit-test]
    uses: ./.github/workflows/pull-unit-lint.yaml
    if: ${{ needs.check-unit-test.outputs.any_modified }}
    secrets: inherit

  check-integration:
    name: Check whether integration tests should run based on the changed files
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        id: changed-files
        with:
          files_ignore_yaml: |
            docs:
              - docs/**
              - '**/*.md'
            performance_tests:
              - tests/performance/**
            owner_files:
              - OWNERS
              - CODEOWNERS
            sec_scanners:
              - sec-scanners-config.yaml
            github:
              - .github/** #Ignoring since build job isn't triggered on the workflow directory changes
            github_and_reuse:
              - .github/**
              - .reuse/**
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
  dispatch-integration:
    name: Dispatch integration tests
    needs: [check-integration,wait-for-image-build]
    uses: ./.github/workflows/pull-integration.yaml
    if: ${{ needs.check-integration.outputs.any_modified }}
    secrets: inherit

  check-ui:
    name: Check whether UI tests should run based on the changed files
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        id: changed-files
        with:
          files_yaml: |
            ui-extensions:
              - config/ui-extensions/**
            crd:
              - config/crd/**
            ui-tests:
              - tests/ui/**
              - .github/workflows/ui-tests.yaml
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
  dispatch-ui:
    name: Dispatch UI tests
    needs: [check-ui,wait-for-image-build]
    uses: ./.github/workflows/ui-tests.yaml
    if: ${{ needs.check-ui.outputs.any_modified }}
    secrets: inherit
