name: Pull Request pipeline
on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]
    branches:
      - main
      - 'release-**'
jobs:
  check-unit-test:
    name: Check whether unit test & lint should run based on the changed files
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        id: changed-files
        with:
          files_ignore_yaml: |
            docs:
              - 'docs/**'
              - '**/*.md'
            performance_tests:
              - 'tests/performance/**'
            owner_files:
              - 'OWNERS'
              - 'CODEOWNERS'
            sec_scanners:
              - 'sec-scanners-config.yaml'
            dependabot:
              - './github/dependabot.yml'
            hidden_files:
              - ".**"
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
  dispatch-unit-test:
    name: Dispatch unit test
    needs: [check-unit-test]
    uses: ./.github/workflows/pull-unit-lint.yaml
    if: ${{ needs.check-unit-test.outputs.any_modified }}
    secrets: inherit

  check-integration:
    name: Check whether integration tests should run based on the changed files
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        id: changed-files
        with:
          files_ignore_yaml: |
            docs:
              - 'docs/**'
              - '**/*.md'
            performance_tests:
              - 'tests/performance/**'
            owner_files:
              - 'OWNERS'
              - 'CODEOWNERS'
            sec_scanners:
              - 'sec-scanners-config.yaml'
            github:
              - '.github/**' #Ignoring since build job isn't triggered on the workflow directory changes
            hidden_files:
              - '.**'
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
  dispatch-integration:
    name: Dispatch integration tests
    needs: [check-integration]
    uses: ./.github/workflows/pull-integration.yaml
    if: ${{ needs.check-integration.outputs.any_modified }}
    secrets: inherit

  check-ui:
    name: Check whether UI tests should run based on the changed files
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        id: changed-files
        with:
          files_yaml: |
            ui-extensions:
              - 'config/ui-extensions/**'
            crd:
              - 'config/crd/**'
            ui-tests:
              - 'tests/ui/**'
              - '.github/workflows/ui-tests.yaml'
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
  dispatch-ui:
    name: Dispatch UI tests
    needs: [check-ui]
    uses: ./.github/workflows/ui-tests.yaml
    if: ${{ needs.check-ui.outputs.any_modified }}
    secrets: inherit
