# This workflow is responsible for all kinds of integration tests run on pull request.
# Those tests depend on a container image so in the first job we wait for the image build to succeed.

name: Pull Request integration tests

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches:
      - main
      - 'release-**'

jobs:
  filter-changes:
    name: List relevant VCS changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        id: changed-files
        with:
          files_ignore_yaml: |
            docs:
              - 'docs/**'
              - '**/*.md'
            performance_tests:
              - 'tests/performance/**'
            owner_files:
              - 'OWNERS'
              - 'CODEOWNERS'
            sec_scanners:
              - 'sec-scanners-config.yaml'
            github:
              - '.github/**' #Ignoring since build job isn't triggered on the workflow directory changes
            hidden_files:
              - '.**'
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
  wait-for-image-build:
    name: Wait for image build
    needs: [filter-changes]
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false && needs.changed-files.outputs.any_modified }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/wait-for-job-succeed-or-fail
        with:
          job-name: 'pull-istio-operator-build'
          github-auth-token: ${{ secrets.GITHUB_TOKEN }}

  k8s-compatibility-test:
    name: Kubernetes version compatibility test
    runs-on: ubuntu-latest
    needs: [wait-for-image-build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/k8s-compatibility-test
        with:
          operator-image-name: "europe-docker.pkg.dev/kyma-project/dev/istio-manager:PR-${{github.event.number}}"

  istio-upgrade-integration-test:
    name: Istio upgrade integration test
    runs-on: ubuntu-latest
    needs: [wait-for-image-build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/upgrade-integration-test
        with:
          operator-image-name: "europe-docker.pkg.dev/kyma-project/dev/istio-manager:PR-${{github.event.number}}"
          target_branch: ${{ github.base_ref }}

  istio-integration-test:
    name: Istio integration test
    runs-on: ubuntu-latest
    needs: [wait-for-image-build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/integration-test
        with:
          evaluation: false
          operator-image-name: "europe-docker.pkg.dev/kyma-project/dev/istio-manager:PR-${{github.event.number}}"
          servers-memory: "16g"
          agents: 2

  istio-integration-test-evaluation:
    name: Istio integration test evaluation
    runs-on: ubuntu-latest
    needs: [wait-for-image-build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/integration-test
        with:
          evaluation: true
          operator-image-name: "europe-docker.pkg.dev/kyma-project/dev/istio-manager:PR-${{github.event.number}}"
          servers-memory: "4g"
          agents: 0
