name: UI Tests

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]
    paths:
      - 'config/ui-extensions/**'
      - 'config/crd/**'
      - 'tests/ui/**'
      - '.github/workflows/ui-tests.yaml'
    branches:
      - "main"
      - 'release-**'

jobs:
  filter-changes:
    name: List relevant VCS changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        id: changed-files
        with:
          files_yaml: |
            ui-extensions:
              - 'config/ui-extensions/**'
            crd:
              - 'config/crd/**'
            ui-tests:
              - 'tests/ui/**'
              - '.github/workflows/ui-tests.yaml'
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
  wait-for-image-build:
    name: Wait for image build
    needs: [filter-changes]
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false && needs.changed-files.outputs.any_modified }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/wait-for-job-succeed-or-fail
        with:
          job-name: 'pull-istio-operator-build'
          github-auth-token: ${{ secrets.GITHUB_TOKEN }}

  run-ui-tests:
    name: Run UI tests
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: [wait-for-image-build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run tests
        run: |
          sudo echo "127.0.0.1 local.kyma.dev" | sudo tee -a /etc/hosts
          wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | sudo bash
          IMG=europe-docker.pkg.dev/kyma-project/dev/istio-manager:PR-${{ github.event.number }} ./tests/ui/scripts/k3d-ci-kyma-dashboard-integration.sh prod
      - uses: actions/upload-artifact@v4
        if: always()
        name: Export Cypress output
        with:
          name: cypress
          path: tests/ui/cypress/
